config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :trips do
    resources :bookmarks, only: [:index, :create, :new,:update]
    resources :landmarks, only: [:index, :edit, :destroy, :show, :update]
    resources :routes, only: [:index, :create, :new, :edit, :destroy, :show, :update ]do
      resources :landmarks, only: [:create, :new]
      resources :tags, only: [:create, :new]
    end
    resources :comments, only: [:index, :create, :new, :edit, :show, :update]
  end
  resources :comments, only: :destroy
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  has_one_attached :photo
  belongs_to :route
  has_one :trip, through: :route
  validates :title, :location, :description, presence: true
  # validates :photo, attached: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  def index
    @landmarks = Landmark.all
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @landmark = Landmark.new
    @route = Route.find(params[:route_id])
    @route_icons = {
      plane: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108118/plane-solid_xmddzb.svg",
      train: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108196/train-subway-solid_vdic1m.svg",
      ferry: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107398/ferry-solid_dhpijy.svg",
      yacht: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108358/sailboat-solid_xm2vkv.svg",
      car: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107399/car-solid_rqbpth.svg",
      bus: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107398/bus-solid_r60kus.svg",
      motorbike: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108470/motorcycle-solid_sm5irb.svg",
      first_location: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107398/location-dot-solid_zgly27.svg"
    }
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @landmark = Landmark.new(landmark_params)
    @route = Route.find(params[:route_id])
    @landmark.route = @route
    if @landmark.save!
      redirect_to new_trip_route_landmark_path(@trip, @route)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @landmark = Landmark.find(params[:id])
    @landmark.update
    redirect_to trip_landmarks_path(@landmark)
  end

  def show
    @landmark = Landmark.find(params[:id])
  end

  def destroy
    @landmark = Landmark.find(params[:id])
    @landmark.destroy
    redirect_to trips_path
  end

  private

  def landmark_params
    params.require(:landmark).permit(:title, :location, :description, :photo)
  end
end

app/views/landmarks/new.html.erb
<div id="container-flex" data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
  <div class="container-width" id="bg-blue" data-controller="add-method" >
    <%= link_to  new_trip_route_path(@trip) do %>
      <div style="color:black;" class="fa-solid fa-delete-left"> </div>
    <% end %>
      <h1>Step Three</h1>
      <% if @trip.routes.count == 1 %>
        <h5>Please add at least one landmark or highlight from your time in:</h5>
        <%# The route card for a single route %>
        <div class="create-route">
          <div class="create-icon">
            <img src="<%= @route_icons[@route.method.to_sym.downcase] %>">
          </div>
          <p><strong> <%= @route.destination.truncate(30) %></strong></p>
        </div>
        <%# The routes landmark cards  %>
        <% @route.landmarks.each do |landmark| %>
          <div class="route-landmark">
            <%=cl_image_tag landmark.photo.key, class: "route-landmark-img"  %>
            <div class="route-landmark-info">
              <h5><strong><%= landmark.title.truncate(14) %></strong></h5>
            </div>
          </div>
        <% end %>
        <div class="add-travel" data-add-method-target="button">
          <h2>Add landmark</h2>
          <i class="fa-solid fa-circle-plus" data-action="click->add-method#displayForm click->address-autocomplete#revealMap"></i>
        </div>
        <div class="d-none" data-add-method-target="form" >
          <%= simple_form_for([@trip, @route, @landmark]) do |f| %>
          <%= f.input :title, label: "Name", required: false, label_html: { class:"simple-form-style" }%>
          <%= f.input :description, label: "Description", required: false, label_html: { class:"simple-form-style" }%>
          <%# f.input :location, label: "Landmark address"%>

          <%=f.input :location,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, required: false%>
          <div data-address-autocomplete-target="search" class="simple-form-style"></div>

          <%= f.input :photo, label: "Photo", as: :file, required: false, label_html: { class:"simple-form-style" }%>
          <%= f.submit 'Add Landmark', class: "btn btn-flat mb-4"%>
          <% end %>
        </div>
        <% if @route.landmarks.count > 0 %>
          <a><%= link_to "Create trip!", trip_path(@trip), class: "btn btn-light mb-4" %></a>
        <% end %>
      <% else %>
        <h5>Please add at least one landmark or highlight from your time in:</h5>

        <div class="create-route">
          <div class="create-icon">
            <img src="<%= @route_icons[@route.method.to_sym.downcase] %>">
          </div>
          <p><strong> <%= @route.destination.truncate(30) %></strong></p>
        </div>

        <% @route.landmarks.each do |landmark| %>
          <div class="route-landmark">
            <%=cl_image_tag landmark.photo.key, class: "route-landmark-img"  %>
            <div class="route-landmark-info">
              <h5><strong><%= landmark.title.truncate(14) %></strong></h5>
            </div>
          </div>
        <% end %>
        <div class="add-travel" data-add-method-target="button">
          <h2>Add landmark</h2>
          <i class="fa-solid fa-circle-plus" data-action="click->add-method#displayForm click->address-autocomplete#revealMap"></i>
        </div>
        <div class="d-none" data-add-method-target="form">
          <%= simple_form_for([@trip, @route, @landmark]) do |f| %>
          <%= f.input :title, label: "Name", required: false, label_html: { class:"simple-form-style" }%>
          <%= f.input :description, label: "Description", required: false, label_html: { class:"simple-form-style" }%>
          <%# f.input :location, label: "Landmark address"%>

          <%=f.input :location,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, required: false%>
          <div data-address-autocomplete-target="search" class="simple-form-style"></div>

          <%= f.input :photo, label: "Photo", as: :file, required: false, label_html: { class:"simple-form-style" }%>
          <%= f.submit 'Add Landmark', class: "btn btn-flat mb-4"%>
          <% end %>
        </div>
          <% if @route.landmarks.count > 0 && @trip.routes.select { |route| route.landmarks.empty? }.empty? != true %>
            <p>Or, if you dont want to add any more landmarks</p>
            <% @route = @trip.routes.select { |route| route.landmarks.empty? }.first %>
            <a><%= link_to "Complete leg", new_trip_route_landmark_path(@trip, @route), class: "btn btn-flat mb-4" %></a>
          <% end %>
          <% if @trip.routes.select { |route| route.landmarks.empty? }.empty?%>
            <a><%= link_to "Create trip!", trip_path(@trip), class: "btn btn-flat mb-4" %></a>
          <% end %>

      <% end %>
  </div>
  <div class="container-width" id="bg-light-blue">
    <h1>Add your landmarks!</h1>
    <h2>Create some landmarks for each destination of your trip.</h2>
    <div class="create-flex">
      <i class="fa-solid fa-circle"></i>
      <i class="fa-solid fa-circle"></i>
      <i class="fa-solid fa-circle" id="grey-icon"></i>
    </div>
    <%=image_tag("landmarks.png")%>
  </div>
</div>