config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :trips do
    resources :bookmarks, only: [:index, :create, :new,:update]
    resources :landmarks, only: [:index, :edit, :destroy, :show, :update]
    resources :routes, only: [:index, :create, :new, :edit, :destroy, :show, :update ]do
      resources :landmarks, only: [:create, :new]
      resources :tags, only: [:create, :new]
    end
    resources :comments, only: [:index, :create, :new, :edit, :show, :update]
  end
  resources :comments, only: :destroy
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_card.html.erb
<div class="card-square">
  <div class="square-1">
    <div class="card-square-img">
      <% if trip.landmarks.present? %>
        <% if trip.landmarks[0].photo.attached? %>
          <%= cl_image_tag trip.landmarks[0].photo.key, height: 300, width: 300, class:"d-block w-100", style:"object-fit: cover" %>
        <% end %>
      <% end %>
    </div>
    <div class="avatar-end">
        <% if trip.user.photo.attached? %>
          <%= cl_image_tag trip.user.photo.key, class: "avatar-card"%>
        <% end %>
    </div>
  </div>
  <div class="card-square-infos">
    <div class="square-2">
      <h5><%= trip.title %></h5>
      <ul>
        <% trip.tags.each do |tag| %>
          <li class="tag">
          <% case tag.title %>
            <% when "Hiking" %>
              <i class="fa-solid fa-person-hiking fa-fw circle-icon"></i>
            <% when "Mountains" %>
              <i class="fa-solid fa-mountain fa-fw circle-icon"></i>
            <% when "City" %>
              <i class="fa-solid fa-city fa-fw circle-icon"></i>
            <% when "Jungle" %>
              <i class="fa-solid fa-leaf fa-fw circle-icon"></i>
            <% when "Beach" %>
              <i class="fa-solid fa-umbrella-beach fa-fw circle-icon"></i>
            <% else %>
              <i></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="days">
      <p id="duration"> <%= trip.duration %> days </p>
    </div>
    <div class="square-3" >
      <% bookmark = Bookmark.find_by(user: current_user, trip: trip) %>
      <div class="likes" data-controller="likes" data-likes-target="likes">
        <button class="like-button-index <%= bookmark ? "red" : "" %>" data-likes-target="like" data-action="click->likes#update">
          <i class="fa-solid fa-heart"></i>
        </button>
        <div class="likes-counter-index" data-likes-target="counter">
          <%= trip.likes %>
        </div>
        <div class="d-none" data-likes-target="formWrapper">
          <% if bookmark %>
            <div data-likes-target="delete">
              <%= bookmark_path(bookmark) %>
            </div>
          <% else %>
            <%= simple_form_for ([trip, Bookmark.new]), data: {likes_target: "form"} do |f| %>
              <%= f.submit %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_bookmark.html.erb
<div class="card-bookmark">
  <div class="bookmark-1">
    <div class="card-bookmark-img">
      <% if trip.landmarks[0].photo.attached? %>
        <%= cl_image_tag trip.landmarks[0].photo.key, height: 150, width: 400, class:"d-block w-100", style:"object-fit: cover" %>
      <% end %>
    </div>
    <div class="avatar-book">
        <% if trip.user.photo.attached? %>
          <%= cl_image_tag trip.user.photo.key, class: "avatar-book"%>
        <% end %>
    </div>
  </div>
  <div class="card-bookmark-infos">
    <div class="bookmark-2">
      <h5><%= trip.title %></h5>
      <ul>
        <% trip.tags.each do |tag| %>
          <li class="tag">
          <% case tag.title %>
            <% when "Hiking" %>
              <i class="fa-solid fa-person-hiking fa-fw circle-icon"></i>
            <% when "Mountains" %>
              <i class="fa-solid fa-mountain fa-fw circle-icon"></i>
            <% when "City" %>
              <i class="fa-solid fa-city fa-fw circle-icon"></i>
            <% when "Jungle" %>
              <i class="fa-solid fa-leaf fa-fw circle-icon"></i>
            <% when "Beach" %>
              <i class="fa-solid fa-umbrella-beach fa-fw circle-icon"></i>
            <% else %>
              <i></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="days">
      <p id="duration"> <%= trip.duration %> days </p>
    </div>
    <div class="bookmark-3" >
      <% bookmark = Bookmark.find_by(user: current_user, trip: trip) %>
      <div class="likes" data-controller="likes" data-likes-target="likes">
        <button class="like-button-index <%= bookmark ? "red" : "" %>" data-likes-target="like" data-action="click->likes#update">
          <i class="fa-solid fa-heart"></i>
        </button>
        <div class="likes-counter-index" data-likes-target="counter">
          <%= trip.likes %>
        </div>
        <div class="d-none" data-likes-target="formWrapper">
          <% if bookmark %>
            <div data-likes-target="delete">
              <%= bookmark_path(bookmark) %>
            </div>
          <% else %>
            <%= simple_form_for ([trip, Bookmark.new]), data: {likes_target: "form"} do |f| %>
              <%= f.submit %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>

app/views/shared/_card_landmark.html.erb
<div class="card-landmark" data-action="click->map#landmark" data-id="<%= id %>">
  <div class="landmark-1">
    <%= cl_image_tag photo, class: "card-landmark-img"%>
    <div class="location-end">
      <a href="#" target="_blank"><i class="fa-sharp fa-solid fa-map-pin"></i> <%= location %><a>
      <div class="card-landmark-infos">
        <div class="landmark-2">
          <h4><%= name %> </h4>
          <p><%= description %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_mytrips.html.erb
<div class="card-mytrips">
  <div class="mytrips-1">
    <div class="card-mytrips-img">
      <% if trip.landmarks[0].photo.attached? %>
        <%= cl_image_tag trip.landmarks[0].photo.key, height: 120, width: 200, class:"d-block w-100", style:"object-fit: cover" %>
      <% end %>
    </div>
  </div>
  <div class="card-mytrips-infos">
      <p><%= trip.title %></p>
    <div class="mytrips-3" >
      <% bookmark = Bookmark.find_by(user: current_user, trip: trip) %>
        <button class="like-button-index <%= bookmark ? "red" : "" %>" data-likes-target="like" data-action="click->likes#update">
          <i class="fa-solid fa-heart"></i>
        </button>
      <div class="likes" data-controller="likes" data-likes-target="likes">
        <div class="likes-counter-index" data-likes-target="counter">
          <%= trip.likes %>
        </div>
        <div class="d-none" data-likes-target="formWrapper">
          <% if bookmark %>
            <div data-likes-target="delete">
              <%= bookmark_path(bookmark) %>
            </div>
          <% else %>
            <%= simple_form_for ([trip, Bookmark.new]), data: {likes_target: "form"} do |f| %>
              <%= f.submit %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-expand-sm footer-light text-center d-flex justify-content-between">
  <div class="footer-copyright">
    TravelPlan - Find your travel inspiration!
  </div>
  <div class="footer-links" id="bottom">
    <a href="https://github.com/conniecasimiro/sellebrity" target="_blank">Home</a>
    <a href="https://github.com/conniecasimiro/sellebrity" target="_blank">About us</a>
    <a href="https://github.com/conniecasimiro/sellebrity" target="_blank">Contact us</a>
    <a href="https://github.com/conniecasimiro/sellebrity" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/drunkpeopledoingthings/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/thepetcollective/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/VancityReynolds?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1369052538121691141%7Ctwgr%5E5aa0ed60cb64caf99d740f29839e52307b0f88c9%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.rd.com%2Farticle%2Ffunniest-twitter-accounts%2F" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/le-wagon/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_iconbar.html.erb
<div class="icon-bar">
  <% if user_signed_in? %>
  <a href= "#top" class="Top"><i class="fa-solid fa-angle-up"></i></a>
  <a href= "/" class="Home"><i class="fa-solid fa-house"></i></a>
  <a href="/trips" class="Explore"><i class="fa-solid fa-earth-americas"></i></a>
  <a href="/trips/new" class="Create"><i class="fa-solid fa-plus"></i></a>
  <a href="/users/<%=current_user.id%>" class="Profile"><i class="fa-solid fa-user"></i></a>
  <a href= "#bottom" class="bottom"><i class="fa-solid fa-angle-down"></i></a>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-travelplan">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo2.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Explore", trips_path, class: "nav-link" %>
        </li>
          <li class="nav-item">
          <%= link_to "Create", new_trip_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "My Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.key.present? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
          <%= image_tag "defav1", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Edit my Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>