config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :trips do
    resources :bookmarks, only: [:index, :create, :new,:update]
    resources :landmarks, only: [:index, :edit, :destroy, :show, :update]
    resources :routes, only: [:index, :create, :new, :edit, :destroy, :show, :update ]do
      resources :landmarks, only: [:create, :new]
      resources :tags, only: [:create, :new]
    end
    resources :comments, only: [:index, :create, :new, :edit, :show, :update]
  end
  resources :comments, only: :destroy
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :trip
  has_many :landmarks
  validates :destination, :method, presence: true
  accepts_nested_attributes_for :landmarks, allow_destroy: true

  geocoded_by :destination
  after_validation :geocode, if: :will_save_change_to_destination?
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
    @route = Route.all
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @route = Route.new
    @route.landmarks.build
    @routes = @trip.routes
    @route_icons = {
      plane: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108118/plane-solid_xmddzb.svg",
      train: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108196/train-subway-solid_vdic1m.svg",
      ferry: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107398/ferry-solid_dhpijy.svg",
      yacht: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108358/sailboat-solid_xm2vkv.svg",
      car: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107399/car-solid_rqbpth.svg",
      bus: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107398/bus-solid_r60kus.svg",
      motorcycle: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670108470/motorcycle-solid_sm5irb.svg",
      first_location: "https://res.cloudinary.com/dblvfwtds/image/upload/v1670107398/location-dot-solid_zgly27.svg"
    }
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @route = Route.new(route_params)
    @route.method = "first_location" if route_params[:method].nil?
    @route.duration = 0 if route_params[:duration].nil?
    @route.trip = @trip
    if @route.save!
      redirect_to new_trip_route_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @route = Route.find(params[:id])
    @route.update
  end

  def destroy
    @route = Route.find(params[:id])
    @route.destroy
  end

  private

  def route_params
    params.require(:route).permit(:destination, :method, :duration, :travel_date)
  end

  def landmark_params
    params.require(:route).permit(landmark_attributes: %i[id title location photo])
  end
end

app/views/routes/new.html.erb
<div id="container-flex" data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
  <div class="container-width" id="bg-blue" data-controller="add-method">
   <%= link_to  new_trip_path(@trip) do %>
      <div style="color:black;" class="fa-solid fa-delete-left"> </div>
    <% end %>
    <h1>Step two</h1>
    <% if current_user.trips.last.routes.empty? %>
      <h5>Where did you first arrive on your trip?</h5>
        <div class="add-travel" data-add-method-target="button">
          <h2>Add Your First Destination</h2>
          <i class="fa-solid fa-circle-plus" data-action="click->add-method#displayForm click->address-autocomplete#revealMap"></i>
        </div>
    <div class="d-none" data-add-method-target="form">
        <%= simple_form_for([@trip, @route]) do |f| %>
          <%= f.input :travel_date, as: :date, html5: true, label: "Date of arrival", required: false, label_html: { class:"simple-form-style" }%>
          <%=f.input :destination,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none simple-form-style"}, required: false%>
          <div data-address-autocomplete-target="search" class="simple-form-style"></div>
          <%= f.submit 'Add route', class: "btn btn-flat mb-4"%>
        <% end %>
        <% if current_user.trips.last.routes.count > 1 %>
          <a><%= link_to "skip ", new_trip_route_path(@trip), class: "btn btn-flat" %></a>
        <% end %>
    </div>
    <% else %>
    <h5 data-add-method-target="title">Did you travel anywhere from <strong><%=@trip.routes.last.destination.truncate(30)%>?</strong></h5>
    <div data-add-method-target="routes">
      <% @routes.each do |route|  %>
        <% if route.method != "first_location" %>
          <img id="route-icon" src="https://res.cloudinary.com/dblvfwtds/image/upload/v1670107398/route-solid_mztkqa.svg">
        <% end %>
        <div class="create-route">
          <div class="create-icon">
            <img src="<%= @route_icons[route.method.to_sym.downcase] %>">
          </div>
          <p><strong> <%= route.destination.truncate(30) %></strong></p>
        </div>
      <% end %>
    </div>
        <div class="add-travel" data-add-method-target="button2">
          <h2>Add Another Destination</h2>
          <i class="fa-solid fa-circle-plus" data-action="click->add-method#displayForm2 click->address-autocomplete#revealMap"></i>
        </div>
      <div class="d-none" data-add-method-target="form2">
        <%= simple_form_for([@trip, @route]) do |f| %>
          <%= f.input :travel_date, as: :date, html5: true, label: "Date of arrival", required: false, label_html: { class:"simple-form-style" }%>

          <%=f.input :destination,
          input_html: {data: {address_autocomplete_target: "address"}, class: "d-none simple-form-style"}, required: false%>

          <div data-address-autocomplete-target="search" class="simple-form-style"></div>

          <%= f.input :method, label: "travel method", collection: [ "Plane", "Train", "Ferry", "yacht", "Motorcycle", "Car", "Bus", ], required: false, label_html: { class:"simple-form-style" }%>
          <%= f.submit 'Add route', class: "btn btn-flat mb-4"%>
        <% end %>
      </div>
      <% unless @trip.routes.empty? %>
        <h5><strong>Or</strong>, if you're finished continue to the next step:</h5>
        <%= link_to "Continue", new_trip_route_landmark_path(@trip, @trip.routes.first), class: "btn btn-light " %><% end %>
      <% end %>
  </div>
  <div class="container-width" id="bg-light-blue">
    <h1>Add your travel methods</h1>
    <h2>Tell us where you went within <%="#{current_user.trips.last.location}"%></h2>
    <div class="create-flex">
      <i class="fa-solid fa-circle"></i>
      <i class="fa-solid fa-circle" id="grey-icon"></i>
      <i class="fa-solid fa-circle"></i>
    </div>
      <%=image_tag("travel_methods.png")%>
  </div>
</div>